[package]
name = "anode"
version = "0.1.0"
edition = "2021"
readme = "../README.md"
authors = ["Emil Koutanov"]
license = "MIT"
description = "Concurrency library for Rust."
repository = "https://github.com/obsidiandynamics/anode"

[dev-dependencies]
rand = "0.8.5"
