[package]
name = "libmutex-bench"
version = "0.0.0"
edition = "2021"

[dependencies]
libmutex = { version = "0.1.0", path = "../libmutex" }
parking_lot = { version = "0.12.1" }

[[bin]]
name = "rwlock"
path = "src/rwlock.rs"
